name: Keep Render App Alive (Daytime + Workdays Only)

on:
  schedule:
    - cron: '*/14 7-17 * * 1-4'
      timezone: 'Asia/Dhaka' 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a ping request to Render
        run: curl -I "https://raintree-xnlz.onrender.com/uptime"
